# tasks file for pull-images

- name: Login to the container registry
  containers.podman.podman_login:
    registry: "{{ container_registry }}"
    username: "{{ container_registry_username }}"
    password: "{{ container_registry_password }}"

- name: Pull container images
  containers.podman.podman_image:
    name: "{{ item }}"
  loop: "{{ images }}"
...
