---
#
# Vars for collectd-generic
#

collectd_packages:
  graphite:
    - collectd
    - collectd-turbostat
  satellite6-el7:
    - collectd
    - collectd-postgresql
    - collectd-apache
  satellite6-el8:
    - collectd
    - collectd-disk
    - collectd-postgresql
    - collectd-apache
  docker-hosts:
    - collectd
  capsules:
    - collectd
    - collectd-apache
