---
#
# Vars for collectd-generic
#

collectd_packages:
  graphite:
    - collectd
    - collectd-turbostat
  satellite6-el8:
    - collectd
    - collectd-apache
    - collectd-disk
    - collectd-postgresql
  satellite6-el9:
    - collectd
    - collectd-apache
    - collectd-disk
    - collectd-postgresql
  docker-hosts:
    - collectd
  capsules-el8:
    - collectd
    - collectd-apache
    - collectd-disk
  capsules-el9:
    - collectd
    - collectd-apache
    - collectd-disk
