---
#
# Playbook to install grafana
#

- hosts: grafana
  remote_user: root
  ###gather_facts: no
  vars_files:
    - ../conf/satmon.yaml
  roles:
    - role: rhsm
      when: 
        - offline_install is undefined 
        - "groups['graphite']|first != groups['grafana']|first"
    - { role: grafana }
